# Generated by Django 4.2.7 on 2023-11-07 17:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DutyLocation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "affiliation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ARMY", "Army"),
                            ("NAVY", "Navy"),
                            ("MARINES", "Marines"),
                            ("AIR_FORCE", "Air Force"),
                            ("COAST_GUARD", "Coast Guard"),
                            ("OTHER", "Other"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("provides_services_counseling", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "milmove_duty_locations",
            },
        ),
        migrations.CreateModel(
            name="DutyLocationName",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "duty_location",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="locations.dutylocation"),
                ),
            ],
            options={
                "db_table": "milmove_duty_location_names",
            },
        ),
        migrations.AddIndex(
            model_name="dutylocation",
            index=models.Index(fields=["name"], name="milmove_dut_name_278040_idx"),
        ),
    ]
